# -*- coding: utf-8 -*-
"""Assignment_4_AI1103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C-ZoALCYVxJ4pqSi5RoGPK-_Gbz8R9Q3
"""

import numpy as np
import matplotlib.pyplot as plt

# x co-ordinate
x = np.linspace(0,5,1000000)

# y co-ordinate
y = np.floor(x)

# Plotting
plt.plot(x,y)
plt.grid()
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Relation between X and Y')
plt.show()